'use client';

import { Button } from '@/components/ui/button';
import { Download, Share2 } from 'lucide-react';
import type { UIMessage } from 'ai';

interface DebateExportProps {
  messages: UIMessage[];
  topic: string;
  userPosition: string;
  aiPosition: string;
}

export function DebateExport({
  messages,
  topic,
  userPosition,
  aiPosition,
}: DebateExportProps) {
  const exportDebate = () => {
    const content = `# DebateGPT Session

## Topic: ${topic}

**Your Position:** ${userPosition}
**AI Position:** ${aiPosition}
**Total Exchanges:** ${messages.length}

---

${messages
  .map((msg, idx) => {
    const text = msg.parts
      .filter((part) => part.type === 'text')
      .map((part) => (part as { text: string }).text)
      .join('');

    const speaker = msg.role === 'user' ? 'You' : 'AI Opponent';
    return `### ${speaker} (Round ${Math.ceil((idx + 1) / 2)})\n\n${text}\n`;
  })
  .join('\n---\n\n')}

---

*Generated by DebateGPT - AI-powered debate training platform*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `debate-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareDebate = async () => {
    const text = `I just practiced debating "${topic}" on DebateGPT! ${messages.length} exchanges with an AI opponent. Great way to improve argumentation skills!`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'DebateGPT Session',
          text,
        });
      } catch (err) {
        console.error('Share failed:', err);
      }
    } else {
      navigator.clipboard.writeText(text);
      alert('Share text copied to clipboard!');
    }
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={exportDebate}>
        <Download className="w-4 h-4 mr-2" />
        Export
      </Button>
      <Button variant="outline" size="sm" onClick={shareDebate}>
        <Share2 className="w-4 h-4 mr-2" />
        Share
      </Button>
    </div>
  );
}
